### ISSUE TITLE
Audio data is being streamed too slow

### ISSUE THREAD

**Issue by erpratibha05** [marciovm/Speech-Forever#1]
Hi, 
First of all thank you @marciovm for the code, it helped me a lot.

I am actually facing an issue i.e Error: On streaming recognize stream: ERROR 11 OUT OF RANGE: Audioa data is being streamed too slow. Please stream audio data approximately at real time.

I have been really struggling for a week to get that working, please help.

**Comment by marciovm** [comment]
Sorry, I don't have time to help on this =/.
